export const CATEGORY_COLORS = {
  coffee: "#E8D5A3",
  tea: "#C8DCCA",
  food: "#F0D5C5",
  sweet: "#F0C8C8",
};

export const menuItems = [
  // Coffee Category
  {
    id: "c1",
    name: "Signature Espresso",
    category: "coffee",
    emoji: "☕",
    tag: "Classic",
    desc: "A timeless robust espresso.",
    price: 180,
    special: false,
  },
  {
    id: "c2",
    name: "Saffron Latte",
    category: "coffee",
    emoji: "☕",
    tag: "Aromatic",
    desc: "Rich espresso infused with saffron.",
    price: 320,
    special: true,
  },
  {
    id: "c3",
    name: "Cold Brew Float",
    category: "coffee",
    emoji: "☕",
    tag: "Refreshing",
    desc: "Chilled cold brew topped with creamy float.",
    price: 290,
    special: false,
  },
  {
    id: "c4",
    name: "Flat White",
    category: "coffee",
    emoji: "☕",
    tag: "Smooth",
    desc: "Silky steamed milk over ristretto.",
    price: 240,
    special: false,
  },
  {
    id: "c5",
    name: "Caramel Cortado",
    category: "coffee",
    emoji: "☕",
    tag: "Sweet",
    desc: "Balanced espresso with a touch of caramel.",
    price: 260,
    special: false,
  },

  // Tea Category
  {
    id: "t1",
    name: "Jasmine Green Tea",
    category: "tea",
    emoji: "🍵",
    tag: "Floral",
    desc: "Delicate green tea with jasmine blossoms.",
    price: 180,
    special: false,
  },
  {
    id: "t2",
    name: "Masala Chai Latte",
    category: "tea",
    emoji: "🫖",
    tag: "Spiced",
    desc: "Spiced Indian tea blended with steamed milk.",
    price: 200,
    special: true,
  },
  {
    id: "t3",
    name: "Rose Hibiscus Cooler",
    category: "tea",
    emoji: "🌺",
    tag: "Fruity",
    desc: "Chilled floral infusion of rose and hibiscus.",
    price: 220,
    special: false,
  },

  // Food Category
  {
    id: "f1",
    name: "Avocado Toast",
    category: "food",
    emoji: "🥑",
    tag: "Healthy",
    desc: "Smashed avocado on artisanal sourdough.",
    price: 340,
    special: false,
  },
  {
    id: "f2",
    name: "Butter Croissant",
    category: "food",
    emoji: "🥐",
    tag: "Flaky",
    desc: "Classic all-butter French pastry.",
    price: 160,
    special: true,
  },
  {
    id: "f3",
    name: "Caprese Panini",
    category: "food",
    emoji: "🥪",
    tag: "Italian",
    desc: "Fresh mozzarella, tomatoes, and basil on grilled bread.",
    price: 380,
    special: false,
  },

  // Sweets Category
  {
    id: "s1",
    name: "Tiramisu",
    category: "sweet",
    emoji: "🍰",
    tag: "Decadent",
    desc: "Coffee-soaked ladyfingers with mascarpone cream.",
    price: 280,
    special: true,
  },
  {
    id: "s2",
    name: "Chocolate Lava Cake",
    category: "sweet",
    emoji: "🍫",
    tag: "Indulgent",
    desc: "Warm chocolate cake with a molten center.",
    price: 320,
    special: false,
  },
  {
    id: "s3",
    name: "Berry Cheesecake",
    category: "sweet",
    emoji: "🍓",
    tag: "Tangy",
    desc: "Creamy cheesecake topped with fresh berries.",
    price: 300,
    special: false,
  },
];
